---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: r2dbc-bom

outputs:
- name: r2dbc-bom-artifactory

caches:
- path: maven

run:
  path: r2dbc-bom/ci/build.sh
